### ISSUE TITLE
App crashes on volunteer available orders

### ISSUE THREAD

**Issue by Vek0n** [Vek0n/Korona-Zakupy-Android-App#6]
It's possible that bug is on servers side. App crashes after person in quarantine deleted an order and volunteer browse through available orders list.

**Comment by Vek0n** [comment]
Bug is related with this issue: https://github.com/Vek0n/Korona-Zakupy-WebAPI/issues/6

**Comment by kivix221** [comment]
Fixed see Vek0n/Korona-Zakupy-WebAPI#6
